### PR TITLE
Hsup package

### PR DESCRIPTION
**Pull request by sclasen**
move everything to hsup package, main method to cmd/hsup/main.go

### CODE REVIEW

**Comment by fdr** [comment]
While I grok and appreciate the principle of this, Why Now?

**Comment by sclasen** [comment]
Mostly to facilitate having/ experimenting with different binaries

Perhaps 

* hsup-single run a single supervised process, in docker with slug cmd env on the command line

* hsup-control client side of the control api, get status/control processes

Or use the hsup guts as a library, etc

**Comment by fdr** [comment]
Okay, I'm inclined to say let's do it. 

Here are some less consequential words for texture:

I'm a little leery of Go projects that mushroom out too many binaries that are closely related (e.g. as much as I like packer, it's just *huge* in space usage in aggregate, terraform too...really noticeable when you start vendoring into projects).  However, the extreme of *exactly one* binary is not a goal for me either.

As an alternative, building out the subcommand and usage generation architecture in "main" is an alternative to this.  That's a bit more like how the quite large "go" tool itself is organized (iirc it does some of both). And, understandably, whipping up a hack in another package can be easier than integrating (though, the situation reverses when one needs to mess with some internals, so I also don't want to go split-crazy).

The other reason I'm interested in this making "godoc" look nice. For "main" packages it won't bother generating docs and I think that hsup has enough files and logical constructs now that getting an indexed copy of the searchable internals on the internet, would be useful particularly to occasional or new hackers even if hsup is ever only nominally a library.

**Comment by fdr** [comment]
Obsoleted in c571694288c0aa8d83f75675a45e20fc83c25bb5

**Pull request closed without merging**
